ios:
  actions:
    - name: Good Night
      background_color: '#000000'
      label:
        text: Good Night
        color: '#ffffff'
      icon:
        icon: bed-king-outline
        color: '#ffffff'
