ios:
  actions:
    - name: Good Night
      background_color: '#000000'
      label:
        text: Good Night
        color: '#ffffff'
      icon:
        icon: bed-king-outline
        color: '#ffffff'
    - name: Work
      background_color: '#98f36d'
      label:
        text: Work
        color: '#000000'
      icon:
        icon: briefcase-outline
        color: '#000000'
