- platform: template
  switches:
    vacation_mode:
      friendly_name: Vacation Mode
      value_template: "{{ is_state('input_boolean.vacation_mode', 'on') }}"
      icon_template: mdi:palm-tree
      turn_on:
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.vacation_mode
      turn_off:
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.vacation_mode
