alias: Children's Room Mini Switch
mode: restart
use_blueprint:
  path: SeanM/zha-aqara-wireless-mini-switch.yaml
  input:
    aqara_mini_switch: 9959beea1aa127c59c25518950573b87
    button_single_press:
      - service: switch.toggle
        target:
          entity_id: switch.heat_lamp
    button_double_press:
      - service: switch.toggle
        target:
          entity_id: switch.babyphone
