alias: Good Night
triggers:
  - platform: time
    at: '00:00'
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Good Night
  - platform: state
    entity_id: input_boolean.vacation_mode
    to: 'on'
actions:
  - action: switch.turn_off
    target:
      entity_id: group.all_switches
  - action: light.turn_off
    target:
      entity_id: group.all_lights

