alias: Love Mini Switch
description: Allows changing Love Switch in Children's Room. Single press to toggle, double press to turn on for 10 minutes.
mode: restart
use_blueprint:
  path: SeanM/zha-aqara-wireless-mini-switch.yaml
  input:
    aqara_mini_switch: 9959beea1aa127c59c25518950573b87
    button_single_press:
      - service: >
          {% if is_state('switch.love', 'on') %}
            homeassistant.turn_off
          {% else %}
            homeassistant.turn_on
          {% endif %}
        target:
          entity_id: group.love
    button_double_press:
      - condition: state
        entity_id: switch.love
        state: 'off'
      - service: homeassistant.turn_on
        target:
          entity_id: group.love
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        target:
          entity_id: group.love
