alias: Office Mini Switch
mode: restart
use_blueprint:
  path: SeanM/zha-aqara-wireless-mini-switch.yaml
  input:
    aqara_mini_switch: 8f05e0fa818d07064a3e94c256426d6a
    button_single_press:
      # toggle office desk wled light
      - service: light.toggle
        target:
          entity_id: light.office_desk_wled

      # select preset if light was turned on
      - alias: Vacation Mode was turned off
        condition: state
        entity_id: light.office_desk_wled
        state: 'on'
      - service: select.select_option
        target:
          entity_id: select.office_desk_wled_preset
        data:
          option: Morning
    button_double_press:
      - service: switch.toggle
        target:
          entity_id: switch.office_desk_lamp
