alias: Startup Checks
triggers:
  - platform: homeassistant
    event: start
actions:
  - action: frontend.set_theme
    data:
      name: Google - Dark
  - action: notify.discord
    data:
      target: [!secret discord_channel]
      title: Home Assistant
      message: >
        :white_check_mark: System has been started successfully!
