alias: Startup Checks
trigger:
  platform: homeassistant
  event: start
action:
  - service: frontend.set_theme
    data:
      name: Google - Dark
  - service: notify.slack
    data:
      title: Home Assistant
      message: >
        :white_check_mark: System has been started successfully!
