alias: Travel Log Tag
mode: single
trigger:
  - platform: tag
    tag_id: d8011321-ba8d-482b-81ad-41f5dfbedd74
condition:
  condition: not
  conditions:
    - condition: state
      entity_id: device_tracker.pascals_iphone
      state: home
action:
  - variables:
      latitude: '{{ state_attr("device_tracker.pascals_iphone", "latitude") }}'
      longitude: '{{ state_attr("device_tracker.pascals_iphone", "longitude") }}'
  - service: rest_command.travel_log
    data:
      latitude: '{{ latitude }}'
      longitude: '{{ longitude }}'
  - service: notify.mobile_app_pascals_iphone
    data:
      title: Travel Log Created
      message: >
        Current position logged to Travel Log: {{ latitude }}, {{ longitude }}
