alias: Work
triggers:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Work
actions:
  - action: script.turn_on
    target:
      entity_id: script.office_desk_activate
    data:
      variables:
        preset: Morning
