alias: Work
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Work
action:
  - service: script.turn_on
    target:
      entity_id: script.office_desk_activate
    data:
      variables:
        preset: Morning
