# sensor.kugel_power
- platform: integration
  source: sensor.kugel_power
  name: Kugel Energy
  unit_prefix: k
  round: 2

# sensor.lampe_power
- platform: integration
  source: sensor.lampe_power
  name: Lampe Energy
  unit_prefix: k
  round: 2

# sensor.duftlampe_power
- platform: integration
  source: sensor.duftlampe_power
  name: Duftlampe Energy
  unit_prefix: k
  round: 2

# sensor.lichterkette_power
- platform: integration
  source: sensor.lichterkette_power
  name: Lichterkette Energy
  unit_prefix: k
  round: 2

# sensor.baum_power
- platform: integration
  source: sensor.baum_power
  name: Baum Energy
  unit_prefix: k
  round: 2
