title: Office
path: office
icon: mdi:desk-lamp
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards:
            - type: entities
              title: Climate
              state_color: false
              show_header_toggle: false
              entities:
                - entity: sensor.office_climate_lumi_temperature
                  secondary_info: last-changed
                  name: Temperature
                - entity: sensor.office_climate_lumi_humidity
                  secondary_info: last-changed
                  name: Humidity
                - entity: sensor.office_climate_lumi_pressure
                  secondary_info: last-changed
                  name: Pressure
                - entity: sensor.office_climate_lumi_power
                  secondary_info: last-changed
                  name: Battery
              footer:
                type: graph
                entity: sensor.office_climate_lumi_temperature
                hours_to_show: 48
        - type: vertical-stack
          cards:
            - type: entities
              title: Lights
              state_color: true
              show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: switch.office_desk_lamp
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.office_desk_lamp_power
                      name: false
                - entity: light.office_desk_wled
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.office_desk
                  justify: around
                  colors:
                    - type: call-service
                      service: script.turn_on
                      service_data:
                        entity_id: script.office_desk_activate
                        variables:
                          preset: Morning
                      icon_color: '#09fa88'
                    - type: call-service
                      service: script.turn_on
                      service_data:
                        entity_id: script.office_desk_activate
                        variables:
                          preset: Breathe
                      icon_color: '#a7e5c6'
                    - type: call-service
                      service: script.turn_on
                      service_data:
                        entity_id: script.office_desk_activate
                        variables:
                          preset: Tetris
                      icon_color: '#462a5d'
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
