title: Office
path: office
icon: mdi:desk-lamp
theme: Google - Dark
panel: true
badges: []
cards:
  - type: custom:mod-card
    card:
      type: custom:layout-card
      layout_type: custom:horizontal-layout
      layout:
        max_width: 1000
      cards:
        - type: vertical-stack
          cards: []
        - type: vertical-stack
          cards:
            - type: entities
              title: Lights
              state_color: true
              show_header_toggle: true
              entities:
                - type: custom:multiple-entity-row
                  entity: switch.office_desk_lamp
                  secondary_info: last-changed
                  toggle: true
                  entities:
                    - entity: sensor.office_desk_lamp_power
                      name: false
                - entity: light.office_desk_background
                  secondary_info: last-changed
                - type: custom:rgb-light-card
                  entity: light.office_desk
                  justify: around
                  colors:
                    - hs_color: [30, 95] #
                    - hs_color: [165, 100] #
                    - hs_color: [90, 0] #
                    - hs_color: [280, 27] #
                    - hs_color: [301, 24] #
                    - hs_color: [15, 100] #
    card_mod:
      style: |
        ha-card {
          max-width: calc(100% + 7px);
          margin-top: -8px;
          margin-right: -8px;
          margin-left: -7px;
          transition: none;
        }
