- sensor:
    # pascaliske.dev
    - name: cert_expiry_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # auth.pascaliske.dev
    - name: cert_expiry_auth_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_auth_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # charts.pascaliske.dev
    - name: cert_expiry_charts_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_charts_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # code.pascaliske.dev
    - name: cert_expiry_code_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_code_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # docs.pascaliske.dev
    - name: cert_expiry_docs_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_docs_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # git.pascaliske.dev
    - name: cert_expiry_git_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_git_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # go.pascaliske.dev
    - name: cert_expiry_go_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_go_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # keel.pascaliske.dev
    - name: cert_expiry_keel_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_keel_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # links.pascaliske.dev
    - name: cert_expiry_links_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_links_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # registry.pascaliske.dev
    - name: cert_expiry_registry_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_registry_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # # time.pascaliske.dev
    # - name: cert_expiry_time_pascaliske_dev
    #   unit_of_measurement: Days
    #   icon: mdi:certificate
    #   state: >
    #     {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_time_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
    #     {{ (diff / 60 / 1440) | round(0) }}

    # traefik.pascaliske.dev
    - name: cert_expiry_traefik_pascaliske_dev
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_traefik_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # # travel.pascaliske.dev
    # - name: cert_expiry_travel_pascaliske_dev
    #   unit_of_measurement: Days
    #   icon: mdi:certificate
    #   state: >
    #     {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_travel_pascaliske_dev'), as_timestamp(now())) - as_timestamp(now()) | int %}
    #     {{ (diff / 60 / 1440) | round(0) }}

    # iske.cloud
    - name: cert_expiry_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # alerts.iske.cloud
    - name: cert_expiry_alerts_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_alerts_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # drop.iske.cloud
    - name: cert_expiry_drop_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_drop_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # grafana.iske.cloud
    - name: cert_expiry_grafana_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_grafana_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # homeassistant.iske.cloud
    - name: cert_expiry_homeassistant_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_homeassistant_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # keel.iske.cloud
    - name: cert_expiry_keel_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_keel_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # prometheus.iske.cloud
    - name: cert_expiry_prometheus_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_prometheus_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # status.iske.cloud
    - name: cert_expiry_status_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_status_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # traefik.iske.cloud
    - name: cert_expiry_traefik_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_traefik_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # unifi.iske.cloud
    - name: cert_expiry_unifi_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_unifi_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # vault.iske.cloud
    - name: cert_expiry_vault_iske_cloud
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_vault_iske_cloud'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}

    # tonies.me
    - name: cert_expiry_tonies_me
      unit_of_measurement: Days
      icon: mdi:certificate
      state: >
        {% set diff = as_timestamp(states('sensor.cert_expiry_timestamp_tonies_me'), as_timestamp(now())) - as_timestamp(now()) | int %}
        {{ (diff / 60 / 1440) | round(0) }}
