- sensor:
    # fritzbox downstream
    - name: FRITZ!Box Downstream
      unit_of_measurement: kbit/s
      state: >
        {%- set downstream = states('sensor.fritz_box_7590_kb_s_received') | float -%}
        {{- (downstream * 8) | round(2) -}}

    # fritzbox downstream percentage
    - name: FRITZ!Box Downstream Percentage
      unit_of_measurement: '%'
      state: >
        {%- set downstream = states('sensor.fritz_box_7590_kb_s_received') | float -%}
        {%- set maxDownstream = states('sensor.fritz_box_7590_max_kbit_s_received') | float -%}
        {{- ((downstream * 8) / maxDownstream * 100) | round(2) -}}

    # fritzbox upstream
    - name: FRITZ!Box Upstream
      unit_of_measurement: kbit/s
      state: >
        {%- set upstream = states('sensor.fritz_box_7590_kb_s_sent') | float -%}
        {{- (upstream * 8) | round(2) -}}

    # fritzbox upstream percentage
    - name: FRITZ!Box Upstream Percentage
      unit_of_measurement: '%'
      state: >
        {%- set upstream = states('sensor.fritz_box_7590_kb_s_sent') | float -%}
        {%- set maxUpstream = states('sensor.fritz_box_7590_max_kbit_s_sent') | float -%}
        {{- ((upstream * 8) / maxUpstream * 100) | round(2) -}}

    # fritzbox uptime
    - name: FRITZ!Box Connection Uptime
      state: >
        {%- set uptime = states('sensor.fritz_box_7590_connection_uptime') -%}
        {{- relative_time(uptime | as_datetime) -}}

    # fritzbox public ip
    - name: FRITZ!Box Public IP
      state: >
        {{- states('sensor.fritz_box_7590_external_ip') -}}
